### ISSUE TITLE
KeyError: 'nickname' when signing up with github

### ISSUE THREAD

**Issue by cvzi** [BlitzKraft/saythanks.io#223] opened 2022-05-05 12:18 UTC
**Describe the bug**
When I try to sign up with github I get an error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Desktop/saythanks.io/saythanks/core.py", line 328, in callback_handling
    nickname = user_detail_info['nickname']
KeyError: 'nickname'
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Click on "Create Your Thankfulness Inbox"
2. Click "Sign up with GitHub"
3. Opens github.com 
4. Grant permission on github.com
5. Redirects to `https://saythanks.io/callback?code=AbCdEfG`
6. See error

**Screenshots**
![Screenshot 2022-05-05 at 14-16-52 KeyError 'nickname' __ Werkzeug Debugger](https://user-images.githubusercontent.com/8470684/166921172-48f609ec-6b07-472c-af9c-f820a1075f79.png)

**Comment by wasi-master** [comment] 2022-05-11 09:49
I can reproduce this

**Comment by rachejazz** [comment] 2022-05-17 00:55
same bug persists still :(

**Comment by kgashok** [comment] 2022-05-28 04:55
@cvzi, @rachejazz , @wasi-master
 
 Strange! My saythanks inbox works okay! @Pavithratrdev will coordinate on your errors and ensure they are fixed.

**Comment by rachejazz** [comment] 2022-05-28 05:24
I beleive the inbox works perfectly, it's just that we can't sign up using our github account

**Comment by kgashok** [comment] 2022-05-28 07:53
@rachejazz thanks, we will revert back with a fix shortly.

**Comment by Pavithratrdev** [comment] 2022-06-13 07:18
@cvzi, @rachejazz , @wasi-master : I'm hoping the problem is with the generation of Auth0 keys; it's been fixed now. 
Could you please make sure the same.

**Comment by cvzi** [comment] 2022-06-13 13:16
Yes it works for me

**Comment by rachejazz** [comment] 2022-06-13 16:01
Works now. Thank you so much!

**Comment by wasi-master** [comment] 2022-06-14 07:24
Working for me as well 👍

**Closed** 2022-06-14 11:09 UTC
Labels: bug, good first issue
